/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4jc6upl5izh
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function Home() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center  bg-gradient-to-r from-[#5a189a] to-[#7b2cbf]  justify-between">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <BanknoteIcon className="h-10 w-10" />
          <span className="font-bold text-4xl mx-5 ">Paynest</span>
        </Link>
        <nav className="flex gap-4 sm:gap-6">
         
          <Link
            href="#"
            className="inline-flex h-10 items-center justify-center rounded-md bg-[#9d4edd] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#7b2cbf] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}>
            Login
          </Link>
          <Link
            href="#"
            className="inline-flex h-10 items-center justify-center rounded-md border border-[#9d4edd] bg-transparent px-8 text-sm font-medium text-white shadow-sm transition-colors hover:bg-[#9d4edd] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}>
            Sign Up
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section
          className="w-full flex items-centre py-12 md:py-24 lg:py-32 bg-gradient-to-r from-[#5a189a] to-[#7b2cbf]">
          <div
            className="container px-4 md:px-6 grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_550px]">
            <div className="flex flex-col justify-center space-y-4 text-white">
              <div className="space-y-2">
                <h1
                  className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  Seamless Payments and Wallet Solutions
                </h1>
                <p className="max-w-[600px] text-white/80 md:text-xl">
                  Paynest offers a secure and user-friendly platform for all your payment and wallet needs. Streamline
                  your financial transactions with our cutting-edge technology.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-[#9d4edd] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#7b2cbf] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}>
                  Get Started
                </Link>
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md border border-[#9d4edd] bg-transparent px-8 text-sm font-medium text-white shadow-sm transition-colors hover:bg-[#9d4edd] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}>
                  Learn More
                </Link>
              </div>
            </div>
            <img
              src="/placeholder.svg"
              width="550"
              height="550"
              alt="Hero"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square" />
          </div>
        </section>
        <section className="w-full flex items-centre justify-center py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Key Features</h2>
                <p
                  className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Paynest offers a comprehensive suite of features to streamline your payment and wallet management.
                </p>
              </div>
            </div>
            <div
              className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:grid-cols-3 md:gap-12 lg:gap-16">
              <div className="grid gap-4">
                <div className="flex items-center gap-3">
                  <div className="rounded-full bg-[#9d4edd] p-3 text-white">
                    <LockIcon className="h-6 w-6" />
                  </div>
                  <h3 className="text-lg font-bold">Secure Payments</h3>
                </div>
                <p className="text-muted-foreground">
                  Paynest employs industry-leading security measures to protect your financial transactions.
                </p>
              </div>
              <div className="grid gap-4">
                <div className="flex items-center gap-3">
                  <div className="rounded-full bg-[#9d4edd] p-3 text-white">
                    <WalletIcon className="h-6 w-6" />
                  </div>
                  <h3 className="text-lg font-bold">Integrated Wallet</h3>
                </div>
                <p className="text-muted-foreground">
                  Manage all your payment methods and balances in one convenient digital wallet.
                </p>
              </div>
              <div className="grid gap-4">
                <div className="flex items-center gap-3">
                  <div className="rounded-full bg-[#9d4edd] p-3 text-white">
                    <InfoIcon className="h-6 w-6" />
                  </div>
                  <h3 className="text-lg font-bold">Detailed Analytics</h3>
                </div>
                <p className="text-muted-foreground">
                  Track your financial activities and gain valuable insights with our comprehensive analytics.
                </p>
              </div>
              <div className="grid gap-4">
                <div className="flex items-center gap-3">
                  <div className="rounded-full bg-[#9d4edd] p-3 text-white">
                    <SmartphoneIcon className="h-6 w-6" />
                  </div>
                  <h3 className="text-lg font-bold">Mobile-friendly</h3>
                </div>
                <p className="text-muted-foreground">
                  Enjoy a seamless payment and wallet experience on the go with our mobile-optimized platform.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className=" flex items-centre justify-center w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container px-4 md:px-6">
            <div className="grid gap-10 sm:px-10 md:gap-16 md:grid-cols-2">
              <div className="space-y-4">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Testimonials</div>
                <h2
                  className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  What Our Customers Say
                </h2>
                <div className="grid gap-4">
                  <div className="bg-background rounded-lg p-4">
                    <p className="text-muted-foreground">
                      "Paynest has been a game-changer for our business. The platform is incredibly user-friendly and
                      has streamlined our payment processes."
                    </p>
                    <div className="flex items-center gap-2 mt-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>JD</AvatarFallback>
                      </Avatar>
                      <div>
                        <div className="font-medium">John Doe</div>
                        <div className="text-sm text-muted-foreground">CEO, Acme Inc.</div>
                      </div>
                    </div>
                  </div>
                  <div className="bg-background rounded-lg p-4">
                    <p className="text-muted-foreground">
                      "Paynest has been a game-changer for our business. The platform is incredibly user-friendly and
                      has streamlined our payment processes."
                    </p>
                    <div className="flex items-center gap-2 mt-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" />
                        <AvatarFallback>JD</AvatarFallback>
                      </Avatar>
                      <div>
                        <div className="font-medium">Jane Smith</div>
                        <div className="text-sm text-muted-foreground">CFO, Globex Corp.</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Ready to get started?</div>
                <p
                  className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed">
                  Sign up for Paynest today and experience the future of payments and wallet management.
                </p>
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-[#9d4edd] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#7b2cbf] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}>
                  Get Started
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Paynest. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}>
            Terms of Service
          </Link>
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}>
            Privacy
          </Link>
        </nav>
      </footer>
    </div>)
  );
}

function BanknoteIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="12" x="2" y="6" rx="2" />
      <circle cx="12" cy="12" r="2" />
      <path d="M6 12h.01M18 12h.01" />
    </svg>)
  );
}


function InfoIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>)
  );
}


function LockIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>)
  );
}


function SmartphoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>)
  );
}


function WalletIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1" />
      <path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
